name: switcheddesigns.com
favicon: null
layout_spectrum: 0.84343
typography_spectrum: 0.2846267940476537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffccf'
    - '#5a7f4c'
    - '#84a15e'
    - '#c8b906'
    - '#902c2d'
  brandStrength: 0.8666086825542152
  lightness: 0.014511721907183528
  saturation: 0.873709820676595
  rhythmicContrast: 0.8691263198852539
purpose: []
